config = {
	'message_refresh_length_sec':10,
	'am_pm':True,
	'time_O':True,
	'time_refresh_length_sec':3600,
	'sleep_timer':False,
	'sleep_time_start':23,
	'sleep_time_stop':5,
	'small_font_path':'/fonts/Arial-12.bdf',
	'medium_font_path':'/fonts/Arial-14.bdf',
	'creep_font_path':'/fonts/creep.bdf',
	'creep2_font_path':'/fonts/creep2.bdf',
	'main_color':0x480080,
	'time_color':0x8c8c8c,
	'temp_color':0x805500,
	'description_color':0x006a80,
	'loading_splash_path':'/splashes/loading.bmp',
	'sleep_splash_path':'/splashes/sleep.bmp',
	'weather_source':'http://api.openweathermap.org/data/2.5/weather',
	'weather_units':'imperial',
	'weather_refresh_length_sec': 600,
	'weather_icon_spritesheet_path':'/icons/weather-icons.bmp',
	'weather_icon_width':16,
	'weather_icon_height':16,
	'weather_icon_map':('01', '02', '03', '04', '09', '10', '11', '13', '50'),
	'metro_source':'https://api.wmata.com/StationPrediction.svc/json/GetPrediction/',
	'metro_stations':{'U St':'E03','Dupont':'A03'},
	'metro_refresh_length_sec': 60,
	'metro_icon_spritesheet_path':'/icons/metro-icons.bmp',
	'metro_icon_width':16,
	'metro_icon_height':16,
	'metro_icon_map':{'RD':0, 'OR':1, 'BL':2, 'GR':3, 'YL':4, 'SV':5, 'PR':6},
	'spotify_token_source':'https://accounts.spotify.com/api/token',
	'spotify_playing_source':'https://api.spotify.com/v1/me/player/currently-playing',
	'spotify_refresh_length_sec':5,
	
}